/*      */

DROP TABLE INTERSPC.BEGA_SOURCE_COLUMN CASCADE CONSTRAINTS;

CREATE TABLE INTERSPC.BEGA_SOURCE_COLUMN (SOURCE_COLUMN VARCHAR2 (256 CHAR));

CREATE OR REPLACE PUBLIC SYNONYM BEGA_SOURCE_COLUMN FOR INTERSPC.BEGA_SOURCE_COLUMN;

GRANT DELETE,
      INSERT,
      SELECT,
      UPDATE
   ON INTERSPC.BEGA_SOURCE_COLUMN
   TO CONFIGURATOR;

GRANT SELECT ON INTERSPC.BEGA_SOURCE_COLUMN TO VIEW_ONLY;

INSERT INTO INTERSPC.BEGA_SOURCE_COLUMN
SELECT 'NUM_1' SOURCE_COLUMN FROM DUAL
UNION
SELECT 'NUM_2' FROM DUAL
UNION
SELECT 'NUM_3' FROM DUAL
UNION
SELECT 'NUM_4' FROM DUAL
UNION
SELECT 'NUM_5' FROM DUAL
UNION
SELECT 'NUM_6' FROM DUAL
UNION
SELECT 'NUM_7' FROM DUAL
UNION
SELECT 'NUM_8' FROM DUAL
UNION
SELECT 'NUM_9' FROM DUAL
UNION
SELECT 'NUM_10' FROM DUAL
UNION
SELECT 'CHAR_1' FROM DUAL
UNION
SELECT 'CHAR_2' FROM DUAL
UNION
SELECT 'CHAR_3' FROM DUAL
UNION
SELECT 'CHAR_4' FROM DUAL
UNION
SELECT 'CHAR_5' FROM DUAL
UNION
SELECT 'CHAR_6' FROM DUAL
UNION
SELECT 'BOOLEAN_1' FROM DUAL
UNION
SELECT 'BOOLEAN_2' FROM DUAL
UNION
SELECT 'BOOLEAN_3' FROM DUAL
UNION
SELECT 'BOOLEAN_4' FROM DUAL
UNION
SELECT 'DATE_1' FROM DUAL
UNION
SELECT 'DATE_2' FROM DUAL
UNION
SELECT 'UOM_ID' FROM DUAL
UNION
SELECT 'ATTRIBUTE' FROM DUAL
UNION
SELECT 'TEST_METHOD' FROM DUAL
UNION
SELECT 'CHARACTERISTIC' FROM DUAL
UNION
SELECT 'PROPERTY' FROM DUAL
UNION
SELECT 'CH_2' FROM DUAL
UNION
SELECT 'CH_3' FROM DUAL;

COMMIT;

/*      */


DROP TABLE INTERSPC.BEGA_SPECDATA CASCADE CONSTRAINTS;

CREATE TABLE INTERSPC.BEGA_SPECDATA
(
   PART_NO          VARCHAR2 (18 CHAR),
   REVISION         NUMBER (4),
   SECTION_ID       NUMBER (8),
   SUB_SECTION_ID   NUMBER (8),
   PROPERTY_GROUP   NUMBER (8),
   PROPERTY         NUMBER (8),
   ATTRIBUTE        NUMBER (8),
   HEADER_ID        NUMBER (8),
   SOURCE_COLUMN    VARCHAR2 (256 CHAR),
   VALUE            FLOAT (126),
   VALUE_S          VARCHAR2 (256 CHAR),
   UOM_ID           NUMBER (8),
   TEST_METHOD      NUMBER (8),
   SEQUENCE_NO      NUMBER (8)
);

/*
TABLESPACE BEGA_SPECDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX INTERSPC.IDX_ATTRIBUTE ON INTERSPC.BEGA_SPECDATA
(ATTRIBUTE, ATTRIBUTE_REV)
NOLOGGING
TABLESPACE SPECI
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

*/

CREATE OR REPLACE PUBLIC SYNONYM BEGA_SPECDATA FOR INTERSPC.BEGA_SPECDATA;

GRANT DELETE,
      INSERT,
      SELECT,
      UPDATE
   ON INTERSPC.BEGA_SPECDATA
   TO CONFIGURATOR;

GRANT SELECT ON INTERSPC.BEGA_SPECDATA TO VIEW_ONLY;