DECLARE
   CURSOR c_map
   IS
      SELECT DISTINCT * FROM INTERSPC.BEGA_SPECDATA_MAP;

BEGIN
   FOR r_map IN c_map
   LOOP
      BEGIN
         UPDATE INTERSPC.BEGA_SPECDATA D
            SET D.HEADER_ID = R_MAP.HEADER_ID
          WHERE     TRIM(D.SECTION_ID) = TRIM(R_MAP.SECTION_ID)
                AND TRIM(D.SUB_SECTION_ID) = TRIM(R_MAP.SUB_SECTION_ID)
                AND TRIM(D.PROPERTY_GROUP) = TRIM(R_MAP.PROPERTY_GROUP_ID)
                AND TRIM(D.PROPERTY) = TRIM(R_MAP.PROPERTY_ID)
                AND TRIM(D.ATTRIBUTE) = TRIM(R_MAP.ATTRIBUTE_ID)
                AND TRIM(D.SOURCE_COLUMN) = TRIM(R_MAP.SOURCE_COLUMN);
                
              --  DELETE FROM INTERSPC.BEGA_SPECDATA WHERE HEADER_ID IS NULL; 
      END;
   END LOOP;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      NULL;
   WHEN OTHERS
   THEN
      RAISE;
END;

COMMIT;