DROP TABLE INTERSPC.BEGA_SPECDATA_MAP CASCADE CONSTRAINTS;

CREATE TABLE INTERSPC.BEGA_SPECDATA_MAP
(
   --F_ID                 VARCHAR2(15 CHAR)        NOT NULL,
   --REQUIRE              VARCHAR2(4 CHAR),
   --  SECTION              VARCHAR2(60 CHAR),
   -- SUB_SECTION          VARCHAR2(60 CHAR),
   -- PROPERTY_GROUP       VARCHAR2(60 CHAR),
   -- PROPERTY             VARCHAR2(60 CHAR),
   -- ATTRIBUTE            VARCHAR2(60 CHAR),
   -- HEADER               VARCHAR2(60 CHAR),
   -- UOM                  VARCHAR2(30 CHAR),
   -- REF_TEXT             VARCHAR2(100 CHAR),
   -- FREE_TEXT            VARCHAR2(100 CHAR),
   SECTION_ID            NUMBER (8) NOT NULL,
   SUB_SECTION_ID        NUMBER (8) NOT NULL,
   PROPERTY_GROUP_ID     NUMBER (8) NOT NULL,
   PROPERTY_ID           NUMBER (8) NOT NULL,
   ATTRIBUTE_ID          NUMBER (8) NOT NULL,
   UOM_ID                NUMBER (8),
   test_method           NUMBER (8),
   HEADER_ID             NUMBER (8) NOT NULL,
   -- FREE_TEXTTYPE        NUMBER(8),
   -- REF_TEXTTYPE         NUMBER(8),
   SECTION_SEQUENCE_NO   NUMBER (8),
   -- SOURCE_TABLE         VARCHAR2(30 CHAR),
   SOURCE_COLUMN         VARCHAR2 (30 CHAR)
-- TARGET_TABLE         VARCHAR2(100 CHAR),
-- TARGET_COLUMN        VARCHAR2(100 CHAR)
)
TABLESPACE SPECD
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 128 K
         NEXT 2 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
NOLOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM BEGA_SPECDATA_MAP FOR INTERSPC.BEGA_SPECDATA_MAP;

GRANT DELETE,
      INSERT,
      SELECT,
      UPDATE
   ON INTERSPC.BEGA_SPECDATA_MAP
   TO CONFIGURATOR;

GRANT SELECT ON INTERSPC.BEGA_SPECDATA_MAP TO VIEW_ONLY;